(() => {
  const STORAGE_KEY="dutta_restaurant_data_v2", AUTH_KEY="dutta_admin_auth", PIN="2026";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
  const clone=o=>JSON.parse(JSON.stringify(o));
  const defaults=()=>clone(window.DEFAULT_DATA||{});
  function getData(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||defaults()}catch{return defaults()}}
  function saveData(data,msg="Saved"){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));toast(msg)}
  function toast(msg){let x=$("#toast");if(!x){x=document.createElement("div");x.id="toast";x.className="toast";document.body.appendChild(x)}x.textContent=msg;x.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove("show"),2200)}
  function showLogin(){$("#login").hidden=false;$("#app").hidden=true;setTimeout(()=>$("#pin")?.focus(),50)}
  function showApp(){$("#login").hidden=true;$("#app").hidden=false;page(location.hash.replace("#","")||"overview")}
  function login(){const p=$("#pin"),m=$("#loginMessage");if(p.value.trim()!==PIN){m.textContent="Incorrect PIN.";p.value="";p.focus();return}localStorage.setItem(AUTH_KEY,"1");m.textContent="";showApp()}
  function logout(){localStorage.removeItem(AUTH_KEY);location.hash="";showLogin()}
  function page(name){if(localStorage.getItem(AUTH_KEY)!=="1"){showLogin();return}const valid=["overview","brand","hero","menu","gallery","settings"];if(!valid.includes(name))name="overview";location.hash=name;$$('.side[data-page]').forEach(b=>b.classList.toggle('on',b.dataset.page===name));const c=$("#page");c.className="page";({overview:renderOverview,brand:renderBrand,hero:renderHero,menu:renderMenu,gallery:renderGallery,settings:renderSettings}[name])(c)}
  function field(label,key,value,type="input",extra=""){const attrs=type==='textarea'?`${extra}`:`value="${esc(value)}" ${extra}`;return `<label>${esc(label)}<${type} class="field" data-key="${esc(key)}" ${attrs}>${type==='textarea'?esc(value):''}</${type}>`}
  function renderOverview(c){const d=getData();c.innerHTML=`<div class="pageHead"><div><span class="eyebrow">DASHBOARD</span><h2>Good morning.</h2><p>Manage the restaurant content from one place.</p></div><a class="primary" href="index.html" target="_blank">Open Website ↗</a></div><div class="statGrid"><div class="stat"><b>${d.menu?.length||0}</b><small>Menu items</small></div><div class="stat"><b>${d.gallery?.length||0}</b><small>Gallery images</small></div><div class="stat"><b>${d.brand?.city||"—"}</b><small>City</small></div><div class="stat"><b>₹${d.menu?.[0]?.price||"—"}</b><small>Signature starting price</small></div></div><div class="panel" style="margin-top:16px"><div class="panelHead"><h3>Quick actions</h3></div><div class="actions"><button class="primary" data-go="brand">Edit Restaurant Info</button><button class="primary" data-go="menu">Edit Menu</button><button class="primary" data-go="gallery">Edit Gallery</button><button class="primary" data-go="settings">Backup Data</button></div></div>`;$$('[data-go]').forEach(b=>b.onclick=()=>page(b.dataset.go))}
  function renderBrand(c){const b=getData().brand;c.innerHTML=`<div class="pageHead"><div><span class="eyebrow">BRAND</span><h2>Restaurant Info</h2><p>These details appear across the website.</p></div><button class="primary" id="saveBrand">Save Changes</button></div><div class="panel"><div class="formGrid">${field("Restaurant name","name",b.name)}${field("Tagline","tagline",b.tagline)}${field("Owner","owner",b.owner)}${field("Phone","phone",b.phone)}${field("WhatsApp number (country code)","whatsapp",b.whatsapp)}${field("UPI ID","upi",b.upi)}${field("City","city",b.city)}${field("Opening hours","hours",b.hours)}${field("Address","address",b.address,"textarea","rows='3' class='field' data-key='address'")}</div></div>`;$("#saveBrand").onclick=()=>{const d=getData();$$(".field",c).forEach(x=>d.brand[x.dataset.key]=x.value.trim());saveData(d,"Restaurant info saved")}}
  function renderHero(c){const d=getData();c.innerHTML=`<div class="pageHead"><div><span class="eyebrow">HOMEPAGE</span><h2>Homepage Story</h2><p>Control the cinematic first impression.</p></div><button class="primary" id="saveHero">Save Changes</button></div><div class="panel"><div class="formGrid">${field("Eyebrow","eyebrow",d.hero.eyebrow)}${field("Title","title",d.hero.title)}${field("Emphasis","emphasis",d.hero.emphasis)}${field("Hero image URL","image",d.hero.image)}${field("Description","description",d.hero.description,"textarea","rows='4' class='field' data-key='description'")}</div><img class="heroPreview" src="${esc(d.hero.image)}" style="width:100%;max-height:300px;object-fit:cover;margin-top:15px" onerror="this.style.display='none'"></div><div class="panel"><div class="formGrid">${field("Story eyebrow","storyEyebrow",d.story.eyebrow)}${field("Story title","storyTitle",d.story.title)}${field("Story emphasis","storyEmphasis",d.story.emphasis)}${field("Experience title","expTitle",d.experience.title)}${field("Experience emphasis","expEmphasis",d.experience.emphasis)}${field("Experience image URL","expImage",d.experience.image)}</div><div class="actions"><button class="primary" id="saveStory">Save Story / Experience</button></div></div>`;$("#saveHero").onclick=()=>{const d=getData();["eyebrow","title","emphasis","image","description"].forEach(k=>d.hero[k]=$(`[data-key="${k}"]`,c).value.trim());saveData(d,"Homepage saved")};$("#saveStory").onclick=()=>{const d=getData();d.story.eyebrow=$('[data-key="storyEyebrow"]',c).value.trim();d.story.title=$('[data-key="storyTitle"]',c).value.trim();d.story.emphasis=$('[data-key="storyEmphasis"]',c).value.trim();d.experience.title=$('[data-key="expTitle"]',c).value.trim();d.experience.emphasis=$('[data-key="expEmphasis"]',c).value.trim();d.experience.image=$('[data-key="expImage"]',c).value.trim();saveData(d,"Story saved")}}
  function renderMenu(c){const d=getData();c.innerHTML=`<div class="pageHead"><div><span class="eyebrow">FOOD</span><h2>Menu & Prices</h2><p>Add, edit or remove dishes.</p></div><button class="primary" id="addMenu">+ Add Dish</button></div><div id="menuList"></div>`;const list=$("#menuList");(d.menu||[]).forEach((m,i)=>{list.insertAdjacentHTML("beforeend",`<div class="panel menuItem" data-index="${i}"><div class="panelHead"><h3>Dish ${i+1}</h3><button class="danger deleteMenu" data-index="${i}">Delete</button></div><div class="formGrid">${field("Category","cat",m.cat)}${field("Dish name","name",m.name)}${field("Price","price",m.price)}${field("Image URL","image",m.image)}${field("Description","desc",m.desc,"textarea","rows='3' class='field' data-key='desc'")}</div><img class="menuPreview" src="${esc(m.image)}" onerror="this.style.display='none'"><div class="actions"><button class="primary saveMenu" data-index="${i}">Save Dish</button></div></div>`)}) ;$("#addMenu").onclick=()=>{const d=getData();d.menu=d.menu||[];d.menu.push({cat:"New",name:"New Dish",desc:"Add a description.",price:"0",image:""});saveData(d,"Dish added");renderMenu(c)};$$('.saveMenu').forEach(b=>b.onclick=()=>{const i=+b.dataset.index,box=$(`[data-index="${i}"]`,c),d=getData();d.menu[i]={cat:$('.field[data-key="cat"]',box).value.trim(),name:$('.field[data-key="name"]',box).value.trim(),price:$('.field[data-key="price"]',box).value.trim(),image:$('.field[data-key="image"]',box).value.trim(),desc:$('.field[data-key="desc"]',box).value.trim()};saveData(d,"Dish saved")});$$('.deleteMenu').forEach(b=>b.onclick=()=>{if(!confirm('Delete this dish?'))return;const d=getData();d.menu.splice(+b.dataset.index,1);saveData(d,"Dish deleted");renderMenu(c)})}
  function renderGallery(c){const d=getData();c.innerHTML=`<div class="pageHead"><div><span class="eyebrow">VISUALS</span><h2>Gallery</h2><p>Replace or add restaurant photography.</p></div><button class="primary" id="addGallery">+ Add Image</button></div><div id="galleryList"></div>`;const list=$("#galleryList");(d.gallery||[]).forEach((url,i)=>list.insertAdjacentHTML('beforeend',`<div class="panel galleryItem" data-index="${i}"><div class="panelHead"><h3>Image ${i+1}</h3><button class="danger deleteGallery" data-index="${i}">Delete</button></div><div class="formGrid">${field("Image URL","url",url)}</div><img class="galleryPreview" src="${esc(url)}" onerror="this.style.display='none'"><div class="actions"><button class="primary saveGallery" data-index="${i}">Save Image</button></div></div>`));$("#addGallery").onclick=()=>{const d=getData();d.gallery=d.gallery||[];d.gallery.push("");saveData(d,"Image added");renderGallery(c)};$$('.saveGallery').forEach(b=>b.onclick=()=>{const i=+b.dataset.index,d=getData(),box=$(`[data-index="${i}"]`,c);d.gallery[i]=$('.field[data-key="url"]',box).value.trim();saveData(d,"Gallery saved");renderGallery(c)});$$('.deleteGallery').forEach(b=>b.onclick=()=>{if(!confirm('Delete this image?'))return;const d=getData();d.gallery.splice(+b.dataset.index,1);saveData(d,"Image deleted");renderGallery(c)})}
  function renderSettings(c){c.innerHTML=`<div class="pageHead"><div><span class="eyebrow">SYSTEM</span><h2>Backup & Reset</h2><p>Keep a local backup before changing content.</p></div></div><div class="panel"><div class="panelHead"><h3>Backup</h3></div><p>Download the current browser-stored restaurant data.</p><div class="actions"><button class="primary" id="downloadBackup">Download Backup</button><button class="primary" id="restoreBackup">Restore Backup</button><input id="backupFile" type="file" accept="application/json" hidden></div></div><div class="panel"><div class="panelHead"><h3>Reset</h3></div><p>Restore the original sample data from data.js.</p><button class="danger" id="resetData">Reset to Default Data</button></div>`;$("#downloadBackup").onclick=()=>{const blob=new Blob([JSON.stringify(getData(),null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='dutta-restaurant-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),500);toast('Backup downloaded')};$("#restoreBackup").onclick=()=>$("#backupFile").click();$("#backupFile").onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);if(!data||typeof data!=='object')throw 0;localStorage.setItem(STORAGE_KEY,JSON.stringify(data));toast('Backup restored');page('overview')}catch{toast('Invalid backup file')}};r.readAsText(f);e.target.value=''};$("#resetData").onclick=()=>{if(!confirm('Reset all saved restaurant data to the original defaults?'))return;localStorage.removeItem(STORAGE_KEY);toast('Data reset');page('overview')}}
  function init(){const loginBtn=$("#loginBtn"),logout=$("#logoutBtn"),pin=$("#pin");loginBtn.onclick=login;logout.onclick=logout;pin.onkeydown=e=>{if(e.key==='Enter')login()};$$('.side[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));addEventListener('hashchange',()=>{if(localStorage.getItem(AUTH_KEY)==='1')page(location.hash.slice(1)||'overview')});localStorage.getItem(AUTH_KEY)==='1'?showApp():showLogin()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();