-- Datta Restaurant - Supabase setup
-- Run this SQL once in the Supabase SQL Editor. After setup, normal restaurant changes are done from Admin Panel only.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  phone text not null default '',
  email text not null default '',
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0 check (price >= 0),
  category text not null default 'mains',
  description text not null default '',
  image_url text not null default '',
  badge text not null default '',
  sort_order integer not null default 0,
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Initial menu: inserted only if the menu table is empty.
insert into public.menu_items (name,price,category,description,image_url,badge,sort_order,is_available)
select * from (values
  ('Chicken Biryani',180,'biryani','Aromatic basmati rice with tender chicken & special spices','https://images.unsplash.com/photo-1563379091339-03246963d51a?auto=format&fit=crop&w=700&q=90','Best Seller',1,true),
  ('Paneer Butter Masala',150,'mains','Rich & flavorful paneer in creamy tomato gravy','https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=700&q=90','Chef''s Special',2,true),
  ('Tandoori Chicken',200,'tandoor','Juicy, smoky and full of flavour from the tandoor','https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=700&q=90','Best Seller',3,true),
  ('Chicken Curry',160,'mains','Traditional desi style chicken curry with rich gravy','https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=700&q=90','Popular',4,true),
  ('Veg Fried Rice',90,'chinese','Fresh vegetables with aromatic rice','https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=90','Veg',5,true),
  ('Paneer Tikka',130,'starters','Char-grilled paneer, peppers & mint chutney','https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=700&q=88','',6,true),
  ('Veg Manchurian',100,'chinese','Crispy vegetable balls in spicy Manchurian sauce','https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=700&q=88','',7,true),
  ('Chicken Lollipop',120,'starters','Juicy chicken lollipop, marinated and fried crisp','https://images.unsplash.com/photo-1628294895950-9805252327bc?auto=format&fit=crop&w=700&q=88','',8,true),
  ('Chicken Tikka',180,'tandoor','Boneless chicken, smoky and marinated in spices','https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=700&q=88','',9,true),
  ('Chilli Chicken',110,'chinese','Indo-Chinese chicken with peppers and onion','https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=700&q=88','',10,true),
  ('Masala Dosa',80,'bread','Crispy dosa with potato filling and chutney','https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&w=700&q=88','',11,true)
) as seed(name,price,category,description,image_url,badge,sort_order,is_available)
where not exists (select 1 from public.menu_items);

-- Keep the identity sequence correct even if an older version inserted explicit IDs.
select setval(pg_get_serial_sequence('public.menu_items','id'), coalesce((select max(id) from public.menu_items),0)+1, false);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null default '', email text not null default '', phone text not null default '',
  total numeric(10,2) not null default 0, status text not null default 'New',
  payment_status text not null default 'Pending', payment_method text not null default 'WhatsApp/UPI',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text not null, name text not null, price numeric(10,2) not null default 0, quantity integer not null default 1 check (quantity > 0)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default '', phone text not null default '', date date not null, time time not null,
  guests integer not null default 1, type text not null default 'Table', event text not null default '', status text not null default 'New',
  created_at timestamptz not null default now()
);

-- Upgrade existing menu tables created by an older version.
alter table public.menu_items add column if not exists badge text not null default '';
alter table public.menu_items add column if not exists sort_order integer not null default 0;
alter table public.menu_items add column if not exists updated_at timestamptz not null default now();

alter table public.profiles enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.bookings enable row level security;

create or replace function public.is_admin()
returns boolean language sql security definer set search_path = public stable as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;
grant execute on function public.is_admin() to authenticated;

-- Remove older policies safely, then create the current policies.
drop policy if exists "public can read available menu" on public.menu_items;
drop policy if exists "admins manage menu" on public.menu_items;
drop policy if exists "users read own profile" on public.profiles;
drop policy if exists "users create own profile" on public.profiles;
drop policy if exists "users update own profile" on public.profiles;
drop policy if exists "admins read profiles" on public.profiles;
drop policy if exists "users create own orders" on public.orders;
drop policy if exists "users read own orders" on public.orders;
drop policy if exists "admins manage orders" on public.orders;
drop policy if exists "users create own order items" on public.order_items;
drop policy if exists "users read own order items" on public.order_items;
drop policy if exists "admins manage order items" on public.order_items;
drop policy if exists "users create own bookings" on public.bookings;
drop policy if exists "users read own bookings" on public.bookings;
drop policy if exists "admins manage bookings" on public.bookings;

create policy "public can read available menu" on public.menu_items for select using (is_available = true);
create policy "admins manage menu" on public.menu_items for all using (public.is_admin()) with check (public.is_admin());

create policy "users read own profile" on public.profiles for select using (id = auth.uid());
create policy "users create own profile" on public.profiles for insert with check (id = auth.uid());
create policy "users update own profile" on public.profiles for update using (id = auth.uid()) with check (id = auth.uid());
create policy "admins read profiles" on public.profiles for select using (public.is_admin());

create policy "users create own orders" on public.orders for insert with check (user_id = auth.uid());
create policy "users read own orders" on public.orders for select using (user_id = auth.uid());
create policy "admins manage orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());

create policy "users create own order items" on public.order_items for insert with check (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create policy "users read own order items" on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create policy "admins manage order items" on public.order_items for all using (public.is_admin()) with check (public.is_admin());

create policy "users create own bookings" on public.bookings for insert with check (user_id=auth.uid());
create policy "users read own bookings" on public.bookings for select using (user_id=auth.uid());
create policy "admins manage bookings" on public.bookings for all using (public.is_admin()) with check (public.is_admin());

-- Enable live menu updates for the public website. Safe to run repeatedly.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='menu_items') then
    alter publication supabase_realtime add table public.menu_items;
  end if;
exception when undefined_object then
  null;
end $$;

-- After creating the admin Auth user, run once with its real UUID:
-- update public.profiles set role='admin' where id='YOUR-AUTH-USER-UUID';
