-- Datta Restaurant database setup
-- Run this in Supabase SQL Editor once. Then create at least one admin profile manually.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default '',
  phone text not null default '',
  email text not null default '',
  role text not null default 'customer' check (role in ('customer','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(10,2) not null default 0 check (price >= 0),
  category text not null default 'mains',
  description text not null default '',
  image_url text not null default '',
  is_available boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  customer_name text not null default '',
  email text not null default '',
  phone text not null default '',
  total numeric(10,2) not null default 0,
  status text not null default 'New',
  payment_status text not null default 'Pending',
  payment_method text not null default 'WhatsApp/UPI',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id text not null,
  name text not null,
  price numeric(10,2) not null default 0,
  quantity integer not null default 1 check (quantity > 0)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null default '',
  phone text not null default '',
  date date not null,
  time time not null,
  guests integer not null default 1,
  type text not null default 'Table',
  event text not null default '',
  status text not null default 'New',
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.bookings enable row level security;

-- Security-definer helper avoids recursive RLS checks on profiles.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists(select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

grant execute on function public.is_admin() to authenticated;

-- Public visitors can read only currently available menu items.
create policy "public can read available menu" on public.menu_items
  for select using (is_available = true);

-- Admins can manage the full menu.
create policy "admins manage menu" on public.menu_items
  for all using (public.is_admin()) with check (public.is_admin());

create policy "users read own profile" on public.profiles
  for select using (id = auth.uid());
create policy "users create own profile" on public.profiles
  for insert with check (id = auth.uid());
create policy "users update own profile" on public.profiles
  for update using (id = auth.uid()) with check (id = auth.uid());
create policy "admins read profiles" on public.profiles
  for select using (public.is_admin());

create policy "users create own orders" on public.orders
  for insert with check (user_id = auth.uid());
create policy "users read own orders" on public.orders
  for select using (user_id = auth.uid());
create policy "admins manage orders" on public.orders
  for all using (public.is_admin()) with check (public.is_admin());

create policy "users create own order items" on public.order_items
  for insert with check (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create policy "users read own order items" on public.order_items
  for select using (exists(select 1 from public.orders o where o.id=order_id and o.user_id=auth.uid()));
create policy "admins manage order items" on public.order_items
  for all using (public.is_admin()) with check (public.is_admin());

create policy "users create own bookings" on public.bookings
  for insert with check (user_id=auth.uid());
create policy "users read own bookings" on public.bookings
  for select using (user_id=auth.uid());
create policy "admins manage bookings" on public.bookings
  for all using (public.is_admin()) with check (public.is_admin());

-- After creating your admin Auth user, replace the UUID below and run:
-- update public.profiles set role='admin' where id='YOUR-AUTH-USER-UUID';
